### PR TITLE
Add proxy support using npm config options proxy and https-proxy

### PR DESCRIPTION
**Pull request by aschlosser-tf**
Our usecase requires us to tunnel all of npms connections through a proxy server. This did not work with _node-chromium_. This pull request implements proxy tunneling using the _tunnel_ package and the existing proxy config in npmrc.

Tested on OSX and Windows with HTTPS connections over an HTTP tunnel.

### CODE REVIEW

**Comment by dtolstyi** [comment]
Good job, Alex @aschlosser-tf!

Could you add details about the usage (`npm_config_https_proxy`, `process.env.npm_config_proxy`, `process.env.npm_config_http_proxy` env variables) to `README.md` file?

Thank you!

**Comment by aschlosser-tf** [comment]
Will do. I will also update the package-lock.json as the CI suggests.

**Comment by dtolstyi** [comment]
Great! Thank you Alex!

Kind regards,
Dmytro TOLSTYI


ср, 12 дек. 2018 г. в 11:58, Alex Schlosser <notifications@github.com>:

**Comment by dtolstyi** [comment]
Great! Thank you Alex!

**Comment by dtolstyi** [comment]
Thank you Alex!

**Pull request merged**
